version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db
      - redis
    environment:
      - DB_URL=db:6379
  db:
    image: mongo:4.2.6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  mongodata:
  redisdata:
